"""Deterministic daily report — markdown + HTML.

Shows the Phase 4 thesis-aware classification (Hold/Watch/Accumulate/Trim/Exit) when scoring
has run; otherwise falls back to the Phase 3 technical/risk flag.
"""

from __future__ import annotations

from pathlib import Path

_FLAG_EMOJI = {"ok": "🟢", "watch": "🟡", "risk": "🔴"}
_CLASS_EMOJI = {
    "Accumulate Candidate": "🟢",
    "Hold": "🟢",
    "Watch": "🟡",
    "Trim Candidate": "🟠",
    "Exit Candidate": "🔴",
}
_DISCLAIMER = "Personal informational use, not investment advice."


def _f(x, dec: int = 2, suffix: str = "") -> str:
    return "—" if x is None else f"{x:.{dec}f}{suffix}"


def _change_key(r: dict):
    return r["day_change_pct"] if r["day_change_pct"] is not None else (r.get("ret_1d") or 0)


def _status(r: dict) -> tuple[str, str]:
    if r.get("classification"):
        return _CLASS_EMOJI.get(r["classification"], "⚪"), r["classification"]
    return _FLAG_EMOJI[r["flag"]], r["flag"].upper()


def _needs_attention(r: dict) -> bool:
    if r.get("classification"):
        return r["classification"] not in ("Hold", "Accumulate Candidate")
    return r["flag"] != "ok"


def _reasons(r: dict) -> str:
    txt = r.get("rec_reason") or "; ".join(r.get("reasons") or [])
    return txt or "None"


# ---------- Markdown ----------
def build_markdown(data: dict, narrative: dict | None = None) -> str:
    p = data["portfolio"]
    rows = data["holdings"]
    notes = (narrative or {}).get("holdings") or {}
    scored = any(r.get("classification") for r in rows)
    L: list[str] = []
    L.append(f"# Daily Portfolio Report — {data['run_date']}")
    L.append("")
    L.append(f"> **{_DISCLAIMER}**")
    if not scored:
        L.append("> Flags are preliminary technical/risk signals; thesis-aware classification arrives once scoring runs.")
    else:
        L.append("> Classifications are rule-based; the analyst narrative below is generated by Claude.")
    L.append("")

    if narrative and narrative.get("executive"):
        L.append("## Analyst narrative")
        L.append(narrative["executive"])
        L.append("")

    L.append("## Executive summary")
    day = f", day change **{p['day_change_pct']:+.2f}%**" if p["day_change_pct"] is not None else ""
    L.append(f"- Portfolio value **₹{p['value']:,.0f}**, unrealized P&L **₹{p['total_pnl']:,.0f}**{day}")
    L.append(f"- **{p['attention_count']}** of {p['holdings_count']} holdings need attention")
    fdi = ""
    if p["fii_net"] is not None or p["dii_net"] is not None:
        fdi = f" · FII net ₹{_f(p['fii_net'], 0)} cr · DII net ₹{_f(p['dii_net'], 0)} cr"
    L.append(f"- Top-5 concentration **{p['top5_pct']:.0f}%**{fdi}")
    L.append("")

    attention = [r for r in rows if _needs_attention(r)]
    if attention:
        L.append("## Action queue (needs attention)")
        for r in attention:
            emoji, label = _status(r)
            conf = f" · {r['confidence']} confidence" if r.get("confidence") else ""
            L.append(f"- {emoji} **{r['symbol']}** ({label}{conf}): {_reasons(r)}")
        L.append("")

    movers = [r for r in rows if _change_key(r)]
    if movers:
        movers.sort(key=_change_key, reverse=True)
        L.append("## Top movers (today)")
        for r in movers[:3]:
            L.append(f"- 🔼 **{r['symbol']}** {_change_key(r):+.2f}%")
        for r in movers[-3:][::-1]:
            if _change_key(r) < 0:
                L.append(f"- 🔽 **{r['symbol']}** {_change_key(r):+.2f}%")
        L.append("")

    L.append("## Holdings")
    for r in rows:
        emoji, label = _status(r)
        conf = f" · {r['confidence']} confidence" if r.get("confidence") else ""
        changed = ""
        if r.get("prev_classification") and r["prev_classification"] != r.get("classification"):
            changed = f"  _(was {r['prev_classification']})_"
        L.append(f"### {emoji} {r['symbol']} — {label}{conf}{changed}")
        dc = f" · day {r['day_change_pct']:+.2f}%" if r["day_change_pct"] is not None else ""
        L.append(
            f"- Price ₹{_f(r['ltp'])} (avg ₹{_f(r['avg_price'])}, P&L ₹{_f(r['pnl'], 0)}, "
            f"weight {_f(r['weight_pct'], 1, '%')}){dc}"
        )
        L.append(
            f"- Returns: 1D {_f(r['ret_1d'], 2, '%')} · 5D {_f(r['ret_5d'], 2, '%')} · "
            f"20D {_f(r['ret_20d'], 2, '%')} · vs NIFTY {_f(r['rel_strength'], 1, 'pts')}"
        )
        t50 = "above" if r["above_50dma"] else ("below" if r["above_50dma"] is not None else "?")
        t200 = "above" if r["above_200dma"] else ("below" if r["above_200dma"] is not None else "?")
        L.append(
            f"- Trend: {t50} 50-DMA (₹{_f(r['sma_50'], 1)}) · {t200} 200-DMA (₹{_f(r['sma_200'], 1)}) · "
            f"RSI {_f(r['rsi'], 0)} · drawdown {_f(r['drawdown'], 0, '%')}"
        )
        if r.get("delivery_pct") is not None:
            L.append(f"- Delivery: {_f(r['delivery_pct'], 1, '%')} ({r.get('signal')})")
        L.append(f"- Reasons: {_reasons(r)}")
        note = notes.get(r["symbol"])
        if isinstance(note, dict) and note.get("note"):
            L.append(f"- Analyst: {note['note']} _(thesis {note.get('thesis_status', '?')})_")
        L.append("")

    return "\n".join(L)


# ---------- HTML ----------
_CSS = """
body{font:14px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;max-width:900px;margin:2rem auto;padding:0 1rem;color:#1a1a1a}
h1{font-size:1.5rem} h2{font-size:1.15rem;margin-top:1.6rem;border-bottom:1px solid #eee;padding-bottom:.3rem}
table{border-collapse:collapse;width:100%;font-size:13px} th,td{padding:.4rem .5rem;text-align:right;border-bottom:1px solid #eee}
th:first-child,td:first-child{text-align:left}
.risk,.exit,.trim{color:#c0392b;font-weight:600} .watch{color:#b8860b;font-weight:600} .ok,.hold,.accumulate{color:#27ae60}
.note{color:#666;font-size:12px}
"""


def build_html(data: dict, narrative: dict | None = None) -> str:
    p = data["portfolio"]
    rows = data["holdings"]
    day = f"{p['day_change_pct']:+.2f}%" if p["day_change_pct"] is not None else "—"
    exec_html = ""
    if narrative and narrative.get("executive"):
        exec_html = f"<h2>Analyst narrative</h2><p>{narrative['executive']}</p>"
    parts = [
        f"<style>{_CSS}</style>",
        f"<h1>Daily Portfolio Report — {data['run_date']}</h1>",
        f"<p class='note'>{_DISCLAIMER}</p>",
        exec_html,
        "<h2>Summary</h2><ul>",
        f"<li>Value <b>₹{p['value']:,.0f}</b>, P&amp;L <b>₹{p['total_pnl']:,.0f}</b>, day <b>{day}</b></li>",
        f"<li><b>{p['attention_count']}</b>/{p['holdings_count']} need attention · top-5 {p['top5_pct']:.0f}%</li>",
        "</ul>",
        "<h2>Holdings</h2>",
        "<table><tr><th>Symbol</th><th>LTP</th><th>Day%</th><th>20D%</th><th>vsNIFTY</th>"
        "<th>RSI</th><th>Trend</th><th>Wt%</th><th>Signal</th></tr>",
    ]
    for r in rows:
        t50 = "▲50" if r["above_50dma"] else ("▼50" if r["above_50dma"] is not None else "?")
        t200 = "▲200" if r["above_200dma"] else ("▼200" if r["above_200dma"] is not None else "?")
        _, label = _status(r)
        cls = (r.get("classification") or r["flag"]).split()[0].lower()
        parts.append(
            "<tr>"
            f"<td>{r['symbol']}</td><td>{_f(r['ltp'], 1)}</td>"
            f"<td>{_f(r['day_change_pct'], 2)}</td><td>{_f(r['ret_20d'], 1)}</td>"
            f"<td>{_f(r['rel_strength'], 1)}</td><td>{_f(r['rsi'], 0)}</td>"
            f"<td>{t50} {t200}</td><td>{_f(r['weight_pct'], 1)}</td>"
            f"<td class='{cls}'>{label}</td>"
            "</tr>"
        )
    parts.append("</table>")
    return "\n".join(parts)


# ---------- Writers ----------
def write_report(data: dict, output_dir: Path, narrative: dict | None = None) -> tuple[Path, Path]:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    md_path = output_dir / f"report_{data['run_date']}.md"
    html_path = output_dir / f"report_{data['run_date']}.html"
    md_path.write_text(build_markdown(data, narrative), encoding="utf-8")
    html_path.write_text(build_html(data, narrative), encoding="utf-8")
    return md_path, html_path


def exec_summary_line(data: dict) -> str:
    p = data["portfolio"]
    return f"₹{p['value']:,.0f}, P&L ₹{p['total_pnl']:,.0f}, {p['attention_count']} need attention"
