"""theses table

Revision ID: 1378b2c69550
Revises: ac90cbe7ce56
Create Date: 2026-07-14 16:09:55.946406
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1378b2c69550'
down_revision: Union[str, None] = 'ac90cbe7ce56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('bought_reason', sa.Text(), nullable=True),
    sa.Column('conviction', sa.String(length=16), nullable=True),
    sa.Column('target_weight_pct', sa.Float(), nullable=True),
    sa.Column('exit_if', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theses_symbol'), 'theses', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theses_symbol'), table_name='theses')
    op.drop_table('theses')
    # ### end Alembic commands ###
