"""baseline schema

Revision ID: ac90cbe7ce56
Revises: 
Create Date: 2026-07-13 18:24:12.185686
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac90cbe7ce56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_run_date'), 'events', ['run_date'], unique=False)
    op.create_index(op.f('ix_events_symbol'), 'events', ['symbol'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('ltp', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('weight_pct', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_run_date'), 'holdings', ['run_date'], unique=False)
    op.create_index(op.f('ix_holdings_symbol'), 'holdings', ['symbol'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('output_ref', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_run_date'), 'llm_calls', ['run_date'], unique=False)
    op.create_table('market_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('fii_net', sa.Float(), nullable=True),
    sa.Column('dii_net', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_flow_run_date'), 'market_flow', ['run_date'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('ret_1d', sa.Float(), nullable=True),
    sa.Column('ret_5d', sa.Float(), nullable=True),
    sa.Column('ret_20d', sa.Float(), nullable=True),
    sa.Column('ret_252d', sa.Float(), nullable=True),
    sa.Column('drawdown', sa.Float(), nullable=True),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('vol_spike', sa.Float(), nullable=True),
    sa.Column('rel_strength', sa.Float(), nullable=True),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_run_date'), 'metrics', ['run_date'], unique=False)
    op.create_index(op.f('ix_metrics_symbol'), 'metrics', ['symbol'], unique=False)
    op.create_table('order_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('traded_qty', sa.Float(), nullable=True),
    sa.Column('delivery_qty', sa.Float(), nullable=True),
    sa.Column('delivery_pct', sa.Float(), nullable=True),
    sa.Column('avg_delivery_pct', sa.Float(), nullable=True),
    sa.Column('signal', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_flow_run_date'), 'order_flow', ['run_date'], unique=False)
    op.create_index(op.f('ix_order_flow_symbol'), 'order_flow', ['symbol'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('prev_classification', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_run_date'), 'recommendations', ['run_date'], unique=False)
    op.create_index(op.f('ix_recommendations_symbol'), 'recommendations', ['symbol'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_run_date'), 'reports', ['run_date'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('thesis', sa.Float(), nullable=True),
    sa.Column('fundamental', sa.Float(), nullable=True),
    sa.Column('technical', sa.Float(), nullable=True),
    sa.Column('valuation', sa.Float(), nullable=True),
    sa.Column('news_risk', sa.Float(), nullable=True),
    sa.Column('portfolio_fit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_run_date'), 'scores', ['run_date'], unique=False)
    op.create_index(op.f('ix_scores_symbol'), 'scores', ['symbol'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_kind'), 'snapshots', ['kind'], unique=False)
    op.create_index(op.f('ix_snapshots_run_date'), 'snapshots', ['run_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshots_run_date'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_kind'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_scores_symbol'), table_name='scores')
    op.drop_index(op.f('ix_scores_run_date'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_reports_run_date'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_recommendations_symbol'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_run_date'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_order_flow_symbol'), table_name='order_flow')
    op.drop_index(op.f('ix_order_flow_run_date'), table_name='order_flow')
    op.drop_table('order_flow')
    op.drop_index(op.f('ix_metrics_symbol'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_run_date'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_market_flow_run_date'), table_name='market_flow')
    op.drop_table('market_flow')
    op.drop_index(op.f('ix_llm_calls_run_date'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_holdings_symbol'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_run_date'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_events_symbol'), table_name='events')
    op.drop_index(op.f('ix_events_run_date'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
